spring:
      application:
                 name: SERVICE-GATEWAY
      cloud:
           gateway:
                   routes:
                    - id: ORDER-SERVICE
                      uri: lb://ORDER-SERVICE
                      predicates:
                         - Path=/order/**
                      filters:
                        - name: CircuitBreaker
                          args:
                            name: ORDER-SERVICE
                            fallbackuri: forward:/orderFallback
                    - id: PAYMENT-SERVICE
                      uri: lb://PAYMENT-SERVICE
                      predicates:
                         - Path=/payment/**
                      filters:
                        - name: CircuitBreaker
                          args:
                            name: PAYMENT-SERVICE
                            fallbackuri: forward:/paymentFallback
hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000000

eureka:
      client:
             register-with-eureka: true
             fetch-registry: true
             service-url:
                     defaultZone: http://localhost:8761/eureka/
      instance:
               hostname: localhost

server:
      port: 8083


management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream